language: java
jdk:
  - openjdk8

branches: # Travis CI 를 어느 브랜치가 푸시될 때 수행할지 지
  only:
    - master

# Travis CI 서버의 홈
cache: # gradle 을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정함
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build" # master 브랜치에 push 되었을 때 수행, 프로젝트 내부에 둔 gradlew 을 통해 clean & build 를 수행

# deploy 명령어가 실행되기 전에 수행
# CodeDeploy 는 Jar 파일을 인식하지 못하므로 Jar+ 기타 설정 파일들을 모아 압축함(zip)
before_deploy:
  # 기존 코드
  # - zip -r freelec-springboot2-webservice * # 현재 위치의 모든 파일을 압축(freelec-springboot2-webservice.zip)
  # - mkdir -p deploy # deploy 라는 이름의 디렉토리 생성
  # - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip # 파일 이동
  # 변경된 코드
  - mkdir -p before-deploy # zip 에 포함시킬 파일들을 담을 디렉토리 생성, travis CI 는 S3 로 특정 파일만 업로드가 불가(디렉토리 단위만 업로드 가능하기에 디렉토리 항상 생성)
  - cp scripts/*.sh before-deploy/ # before-deploy 에 zip 파일에 포함시킬 파일들을 저장
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cp before-deploy && zip -r before-deploy * # before-deploy 로 이동 후 전체 압축, zip -r 명령어를 통해 before-deploy 디렉토리 전체 파일을 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/freelec-springboot2-webservice.zip # deploy 로 zip 파일 이동
# S3, CodeDeploy 로 배포 등 외부 서비스와 연동될 행위 선언
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings 에 설정된 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-build-springbootaws # 버킷 명
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private 로
    local_dir: deploy # before_deploy 에서 생성한 디렉토리, 해당 위치의 파일들만 s3 로 전송
    wait-until-deploy: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings 에 설정된 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-build-springbootaws # 버킷 명
    key: freelec-springboot2-webservice.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: freelec-springboot2-webservice # CodeDeploy 애플리케이션 명
    deployment_group: freelec-springboot2-webservice-group # CodeDeploy 배포 그룹 명
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications: # Travis CI 실행 완료 시 알람
  email:
    recipients:
      - 123or@naver.com # 확인할 메일계정
