language: java
jdk:
  - openjdk8

branches: # Travis CI 를 어느 브랜치가 푸시될 때 수행할지 지
  only:
    - master

# Travis CI 서버의 홈
cache: # gradle 을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정함
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build" # master 브랜치에 push 되었을 때 수행, 프로젝트 내부에 둔 gradlew 을 통해 clean & build 를 수행

# CI 실행 완료 시 메일로 알람
notifications: # Travis CI 실행 완료 시 알람
  email:
    recipients:
      - 123or@naver.com # 확인할 메일계정