version: 0.0 # CodeDeploy 버전 표기
os: linux
files:
  - source: / # CodeDeploy 에서 전달해준 파일 중 destination 으로 이동시킬 대상을 지정, 루트경로지정 -> 전체 파일
    destination: /home/ec2-user/app/step3/zip/ # source 에서 지정된 파일을 받을 위치, 이후 Jar 를 실행하는 등은 destination 에서 옮긴 파일들로 진행
    overwrite: yes # 기존에 파일들이 있으면 덮어쓸지를 결정, yes -> 덮어씀

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh # 엔진엑스와 연결되어 있지 않은 스프링 부트를 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # 엔진엑스와 연결되어 있지 않은 Port 로 새 버전의 스프링 부트를 시작
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 스프링 부트가 정상적으로 실행됐는지 확인
      timeout: 60
      runas: ec2-user